AWSTemplateFormatVersion: "2010-09-09"

Description: Creates a CodeArtifact repository

Parameters:
  RepositoryName:
    Type: String
  DomainName:
    Type: String

Resources:
  CodeArtifactDomain:
    Type: AWS::CodeArtifact::Domain
    Properties:
      DomainName: !Ref DomainName

  CodeArtifactRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: !Ref RepositoryName
      DomainName: !GetAtt CodeArtifactDomain.Name
      Upstreams:
        - !GetAtt CodeArtifactNpmStoreRepository.Name

  CodeArtifactNpmStoreRepository:
    Type: AWS::CodeArtifact::Repository
    Properties:
      RepositoryName: "npm-store"
      DomainName: !GetAtt CodeArtifactDomain.Name
      ExternalConnections:
        - public:npmjs
